#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# LeadBridge — Railway Deployment Script
# This script guides you through deploying to Railway.
# Prerequisites:
#   1. GitHub repo with your code pushed
#   2. Railway account (https://railway.app)
#   3. Railway CLI installed: npm install -g @railway/cli
# ─────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════╗"
echo "║    LeadBridge — Railway Deployment Guide        ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─── Step 1: Check prerequisites ──────────────────────────
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"

# Check git
if ! command -v git &> /dev/null; then
    echo -e "${RED}  ✗ Git not found — install from https://git-scm.com${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ Git found${NC}"

# Check Railway CLI
if command -v railway &> /dev/null; then
    echo -e "${GREEN}  ✓ Railway CLI found${NC}"
    HAS_RAILWAY_CLI=true
else
    echo -e "${YELLOW}  ⚠ Railway CLI not found — installing...${NC}"
    npm install -g @railway/cli 2>/dev/null || {
        echo -e "${YELLOW}  ⚠ Could not install Railway CLI. You can use the web dashboard instead.${NC}"
        HAS_RAILWAY_CLI=false
    }
fi

# Check for .env
if [ ! -f "$PROJECT_ROOT/server/.env" ]; then
    echo -e "${YELLOW}  ⚠ server/.env not found — run 'bash scripts/setup.sh' first or manually create it${NC}"
    echo -e "${YELLOW}     For Railway, only JWT_SECRET, JWT_REFRESH_SECRET, and OMNIDIM_API_KEY are required.${NC}"
    echo -e "${YELLOW}     Database and Redis URLs are auto-injected by Railway plugins.${NC}"
fi

echo ""

# ─── Step 2: GitHub repo check ───────────────────────────
echo -e "${YELLOW}[2/6] Checking GitHub remote...${NC}"
REMOTE=$(git remote get-url origin 2>/dev/null || echo "")
if [ -z "$REMOTE" ]; then
    echo -e "${RED}  ✗ No git remote 'origin' found${NC}"
    echo -e "     Push your code to GitHub first:"
    echo -e "     git remote add origin https://github.com/YOUR_USER/leadbridge.git"
    echo -e "     git push -u origin main"
    exit 1
fi
echo -e "${GREEN}  ✓ Git remote: $REMOTE${NC}"

echo -e "${YELLOW}  Checking GitHub connection...${NC}"
if git ls-remote origin &>/dev/null; then
    echo -e "${GREEN}  ✓ GitHub reachable${NC}"
else
    echo -e "${RED}  ✗ Cannot reach GitHub — check your remote URL and internet connection${NC}"
    exit 1
fi

# Check for uncommitted changes
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo -e "${YELLOW}  ⚠ You have uncommitted changes. Commit them before deploying:${NC}"
    git status --short
    echo ""
    read -rp "  Commit all changes? (y/n): " COMMIT_ANSWER
    if [ "$COMMIT_ANSWER" = "y" ]; then
        git add -A
        git commit -m "chore: pre-deployment cleanup"
        git push
        echo -e "${GREEN}  ✓ Changes committed and pushed${NC}"
    else
        echo -e "${YELLOW}  ⚠ Skipping — deploy may use stale code${NC}"
    fi
fi
echo ""

# ─── Step 3: Railway setup instructions ──────────────────
echo -e "${YELLOW}[3/6] Railway Project Setup${NC}"
echo ""
echo -e "  Go to ${CYAN}https://railway.app/dashboard${NC}"
echo ""
echo -e "  1. Click ${GREEN}New Project${NC} → ${GREEN}Deploy from GitHub repo${NC}"
echo -e "  2. Select your leadbridge repository"
echo -e "  3. Railway will auto-detect Node.js and run the build"
echo ""

# Railway Infrastructure
echo -e "${YELLOW}[4/6] Add Infrastructure${NC}"
echo ""
echo -e "  Click ${GREEN}New${NC} → ${GREEN}Database${NC} and add:"
echo -e "    • ${CYAN}PostgreSQL${NC} — copy the DATABASE_URL"
echo -e "    • ${CYAN}Redis${NC} — copy the REDIS_URL"
echo ""

# Environment Variables
echo -e "${YELLOW}[5/6] Set Environment Variables${NC}"
echo ""
echo -e "  In the server service's ${GREEN}Variables${NC} tab, add:"
echo ""
echo -e "  ┌────────────────────────┬──────────────────────────┐"
echo -e "  │ Variable               │ Value                    │"
echo -e "  ├────────────────────────┼──────────────────────────┤"
echo -e "  │ NODE_ENV               │ production               │"
echo -e "  │ PORT                   │ 3000                     │"
echo -e "  │ JWT_SECRET             │ (generated by setup.sh)   │"
echo -e "  │ JWT_REFRESH_SECRET     │ (generated by setup.sh)   │"
echo -e "  │ DATABASE_URL           │ \${{Postgres.DATABASE_URL}}│"
echo -e "  │ DATABASE_URL_PRISMA    │ \${{Postgres.DATABASE_URL}}│"
echo -e "  │ DIRECT_URL             │ \${{Postgres.DATABASE_URL}}│"
echo -e "  │ REDIS_URL              │ \${{Redis.REDIS_URL}}      │"
echo -e "  │ OMNIDIM_API_KEY        │ (from omnidim.io)        │"
echo -e "  │ FRONTEND_URL           │ (your Railway domain)    │"
echo -e "  └────────────────────────┴──────────────────────────┘"
echo ""

# Frontend service
echo -e "${YELLOW}[6/6] Add Frontend Service${NC}"
echo ""
echo -e "  1. Click ${GREEN}New${NC} → ${GREEN}GitHub Repo${NC} → same repo"
echo -e "  2. In service ${GREEN}Settings${NC}, set ${GREEN}Root Directory${NC} to ${CYAN}frontend${NC}"
echo -e "  3. Add frontend variables:"
echo ""
echo -e "  ┌──────────────────────┬─────────────────────────────────┐"
echo -e "  │ Variable             │ Value                           │"
echo -e "  ├──────────────────────┼─────────────────────────────────┤"
echo -e "  │ NEXT_PUBLIC_API_URL  │ https://server-domain/railway.app/api/v1 │"
echo -e "  │ NEXT_PUBLIC_WS_URL   │ wss://server-domain.railway.app │"
echo -e "  │ NEXT_PUBLIC_APP_URL  │ https://frontend-domain.railway.app     │"
echo -e "  └──────────────────────┴─────────────────────────────────┘"
echo ""
echo -e "  4. ${GREEN}Generate Domains${NC}:"
echo -e "     Server → Networking → Generate Domain"
echo -e "     Frontend → Networking → Generate Domain"
echo ""
echo -e "  5. Run migrations in Railway shell:"
echo -e "     ${CYAN}npx prisma db push${NC}"
echo ""

# ─── Optional: Login via CLI ───────────────────────────
echo -e "${CYAN}── Auto-deploy via Railway CLI? ─────────────────${NC}"
read -rp "  Login to Railway CLI? (y/n): " LOGIN_ANSWER
if [ "$LOGIN_ANSWER" = "y" ] && [ "${HAS_RAILWAY_CLI:-false}" = true ]; then
    railway login
    railway link
    echo -e "${GREEN}  ✓ Railway linked${NC}"
    
    echo -e "${YELLOW}  Deploying...${NC}"
    railway up --service leadbridge-server
    echo -e "${GREEN}  ✓ Server deployed${NC}"
    
    echo -e "${YELLOW}  Deploying frontend...${NC}"
    cd "$PROJECT_ROOT/frontend"
    railway up --service leadbridge-frontend
    echo -e "${GREEN}  ✓ Frontend deployed${NC}"
    
    echo -e "${YELLOW}  Opening dashboard...${NC}"
    railway open
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         ✅ Ready to deploy!                      ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  After deployment, verify:"
echo -e "  ${CYAN}curl https://your-server-domain.railway.app/health${NC}"
echo ""
echo -e "  Total setup time: ~20 minutes"
echo ""
